# Generated by Django 3.1.2 on 2020-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_cases',
            name='data',
            field=models.JSONField(default='dict'),
        ),
    ]
